### ISSUE TITLE
about the pretrained model URL

### ISSUE THREAD

**Issue by askies** [sniklaus/revisiting-sepconv#2]
Dear author(sniklaus)

    i run the code run.py and in the estimate->network->init, it has a state_dict_url named 'http://content.sniklaus.com/sepconv/network'
but i cannot enter this website. Firstly i consider my internet refuse to this web, but my friends also cannot enter this web. Could u plz tell me how to enter this web, or could u plz give me another website about the pretrained model. Thanks a lot

**Comment by sniklaus** [comment]
The provided `run.py` automatically downloads the weights for you when you run it, so I am not sure why you want to download them manually. Anyway, the link is not just `http://content.sniklaus.com/resepconv/network` as shown below.

https://github.com/sniklaus/revisiting-sepconv/blob/942a018d853cfbe6510b716dd9cd10c13ec30650/run.py#L374

So try downloading it from: http://content.sniklaus.com/resepconv/network-paper.pytorch

**Comment by askies** [comment]
Yeah, I know what u means. But in fact, i still cannot enter the web you provided, my IDE shows the error named connectionrefusederror:[Error 111] connection refused. I think maybe my internet refused to visit this because I am in china. Do u have another way to download the parameters of model? for example,do u have model PKL file or PT file

**Comment by sniklaus** [comment]
Does this link work? https://www.dropbox.com/s/rftb5sx2a9xmeif

**Comment by askies** [comment]
Hi, my office computer cannot enter 'http://content.sniklaus.com/resepconv/network-paper.pytorch', but my personal computer can. I download it just now and the file is a pytorch file. then I transfer it to my office computer. So the previous way to download the weight is self.load_state_dict(................................), not if i have the pytorch file. which code can i use to directly use the file instead of url. I am a newer AI, so i don't know. Thanks a lot

**Comment by sniklaus** [comment]
Try `mv network-paper.pytorch ~/.cache/torch/hub/checkpoints/resepconv-paper` and see whether it works afterwards.

**Comment by askies** [comment]
hi,which pytorch version did your model use. I encouter a problem maybe because our pytoch version is now the same

**Comment by sniklaus** [comment]
What's the error you are getting?

**Comment by askies** [comment]
in your pytorch file, there is a data.pkl. and when i use torch.load(path of data.pkl) code, there is an error named '_pickle.UnpicklingError: A load persistent id instruction was encountered,but no persistent_load fu'

**Comment by sniklaus** [comment]
It sounds like you tried to extract the pytorch file, don't do that.

Just run `mv network-paper.pytorch ~/.cache/torch/hub/checkpoints/resepconv-paper` and see whether that works.

**Comment by askies** [comment]
i tried it, in the project src directory , i put the network-paper.pytorch, in the project and  i typed this instruction. After it , how can i to then, because the code still has the state_dict_url etc..

**Comment by sniklaus** [comment]
The `load_state_dict_from_url` will only download the model if it doesn't already exist on your computer: https://github.com/pytorch/pytorch/blob/41992791e82566eb977d0a2e062cca0c7fd9d56d/torch/hub.py#L699

The location of this downloaded model on my computer is `~/.cache/torch/hub/checkpoints/resepconv-paper` so if I download the model manually and then move it there, then `load_state_dict_from_url` will do nothing because the model already exists at the location where this function expects it to be. The caveat is that `load_state_dict_from_url` may download the file to a different location. What does `print(torch.hub.get_dir())` print for you?

**Comment by askies** [comment]
/root/.cache/torch/hub

**Comment by askies** [comment]
the program still has the error urllib.error.URLError:<urlopen error [errno 111] Connection refused>

**Comment by sniklaus** [comment]
Did you try `mv network-paper.pytorch /root/.cache/torch/hub/checkpoints/resepconv-paper`?

**Comment by askies** [comment]
yeah, the project src dir has images, middleburry,videos three directories and benchmark.py, run.py, sepconv.py. Then i put network-paper.pytorch with there files in same places. And in this dir, i use mv network-paper.pytorch /root/.cache/torch/hub/checkpoints/resepconv-paper or mv network-paper.pytorch ~/.cache/torch/hub/checkpoints/resepconv-paper.   Then, i still run the run.py, has the url error

**Comment by askies** [comment]
which step did i do wrong

**Comment by sniklaus** [comment]
What does `md5sum /root/.cache/torch/hub/checkpoints/resepconv-paper` return?

**Comment by askies** [comment]
this instruction has error, it said syntaxError:invalid syntax on /.cache/

**Comment by sniklaus** [comment]
That is a shell command, not a Python command. Please try again.

**Comment by askies** [comment]
yeah, it saids 7ce6c2854ee59eaa592013f29a2e3dd6     /root/.cache/torch/hub/checkpoints/resepconv-paper

**Comment by sniklaus** [comment]
Not sure why it doesn't pick it up. At this point the easiest might be to just change:

https://github.com/sniklaus/revisiting-sepconv/blob/942a018d853cfbe6510b716dd9cd10c13ec30650/run.py#L374

To:

```
self.load_state_dict(torch.load('network-paper.pytorch')) 
```

**Comment by askies** [comment]
thanks, it works now

**Comment by askies** [comment]
I still have last question. this net can interpolate middle frame1.5 of frame1 and frame2. Does it only produce one frame? so if i want to interpolate three frames, firsly i can interpolate frame1.5 of frame1and 2. Then interpolate frame 1.25 of frame1 and frame1.5. And interpolate frame 1.75 of frame 1.5 and frame 2. so i get total five frames, frame1 1.25 1.5 1.75 2. Is it right,thanks

**Comment by sniklaus** [comment]
Yes, that is correct - you can recursively continue interpolating frames to get more than just a single one.
