### ISSUE TITLE
Cupy warning "cupy.cuda.compile_with_cache has been deprecated in CuPy v10"

### ISSUE THREAD

**Issue by JohnTravolski** [sniklaus/revisiting-sepconv#5]
With the following configuration:
```
Windows 10
Python 3.8
cupy-cuda11x                 11.0.0
torch                        1.12.1+cu116
NVidia GPU Computing Toolkit 11.7
```
I get the warning
`C:\Program Files\Python\Python38\lib\site-packages\cupy\cuda\compiler.py:460: UserWarning: cupy.cuda.compile_with_cache has been deprecated in CuPy v10, and will be removed in the future. Use cupy.RawModule or cupy.RawKernel instead.`
when I run
`python run.py --model paper --one ./images/one.png --two ./images/two.png --out ./out.png`
Any thoughts on how to fix this?

**Comment by sniklaus** [comment]
The warning just means that the way the CUDA kernel is computed is deprecated and will fail in future versions of CuPy - it doesn't change the outcome otherwise.

**Comment by sniklaus** [comment]
Closing this for now, feel free to reopen in case there are any other concerns with this - thanks!
